name: Release Events
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v5

      - name: 🚀 Deploy
        uses: ./.github/actions/deploy
        timeout-minutes: 15
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notifications
    runs-on: ubuntu-latest
    needs: deploy-prod
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Release Notifier
        uses: agrc/release-issue-notifications-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create deployment notification
        if: github.event.release.prerelease == false
        uses: agrc/service-now-worknote-action@v1
        with:
          repo-token: ${{ github.token }}
          username: ${{ secrets.SN_USERNAME }}
          password: ${{ secrets.SN_PASSWORD }}
          instance-name: ${{ secrets.SN_INSTANCE }}
          table-name: ${{ secrets.SN_TABLE }}
          system-id: ${{ secrets.SN_SYS_ID }}
